#!/usr/bin/env bash
# generate-workflow.sh — Emit .github/workflows/deploy.yml from coolify.yaml.
# Implements GHCR same-image promotion. Smoke test is the gate: staging pass → auto-promote to prod.
#
# build.context and build.dockerfile are read from coolify.yaml.
# Defaults: context = '.' (repo root), dockerfile = './Dockerfile'.
# For nested-app repos (e.g. ai-upskilling/skillmap), set build.context in coolify.yaml (e.g. ./skillmap).
#
# IMPORTANT — no env-specific --build-arg is passed.
# The whole point of same-image promotion is that staging and production run the
# IDENTICAL image bytes (same SHA tag). Baking NEXT_PUBLIC_BASE_URL (or any other
# env-specific value) at build time would require separate builds per environment,
# defeating the model. Instead, all env-specific values are injected at container
# startup by Coolify via the Doppler-managed DOPPLER_TOKEN. The Dockerfile keeps
# ARG NEXT_PUBLIC_BASE_URL="" with an empty default for forward-compat, but this
# generator deliberately omits it from the build-args.
#
# Exception: GIT_SHA and BUILD_TIMESTAMP are identity-only build-args — their values
# are identical across staging and production (same commit, same timestamp), so they
# do NOT break same-image promotion. They bake OCI revision/created labels into the image.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib-coolify-api.sh"

YAML_PATH="${1:-./coolify.yaml}"
[ -f "$YAML_PATH" ] || { echo "ERROR: $YAML_PATH not found" >&2; exit 1; }

# Determine the output path — relative to the directory containing coolify.yaml
OUT_DIR="$(cd "$(dirname "$YAML_PATH")" && pwd)/.github/workflows"
OUT_PATH="$OUT_DIR/deploy.yml"

eval "$(python3 "$SCRIPT_DIR/lib-config.py" emit-yaml-workflow-vars "$YAML_PATH")"

# When called from init.sh (before /setup-coolify provisioning), app IDs are null (~).
# Use placeholder strings so the workflow file is still generated; the actual UUIDs
# and COOLIFY_URL will be embedded when /setup-coolify (provision) regenerates this file.
NEEDS_PROVISION=false
if [ -z "$STAGING_APP_UUID" ] || [ -z "$PROD_APP_UUID" ]; then
  NEEDS_PROVISION=true
  STAGING_APP_UUID="${STAGING_APP_UUID:-REPLACE_WITH_COOLIFY_APP_ID_STAGING}"
  PROD_APP_UUID="${PROD_APP_UUID:-REPLACE_WITH_COOLIFY_APP_ID_PRODUCTION}"
  echo "INFO: coolify_app_ids not yet set — workflow will contain placeholder UUIDs." >&2
  echo "      Run /setup-coolify (provision) after setting up Doppler to replace them." >&2
fi

if [ "$NEEDS_PROVISION" = "false" ]; then
  coolify_load_server "$SERVER_ALIAS"   # sets COOLIFY_URL
else
  # No coolify.json available yet (or app IDs not provisioned) — use placeholder URL.
  COOLIFY_URL="https://REPLACE_WITH_YOUR_COOLIFY_URL"
fi

# GHCR package name from the tag-stripped image path — REGISTRY_IMAGE may
# carry a :tag suffix which must not leak into the ghcr-cleanup package name.
PACKAGE=$(echo "$REGISTRY_IMAGE_NAME" | awk -F'/' '{print $3}')

mkdir -p "$OUT_DIR"

cat > "$OUT_PATH" << YAML
# Auto-generated by ~/.claude/skills/setup-coolify/scripts/generate-workflow.sh
# Source: $YAML_PATH
# Pattern: GHCR same-image promotion. Smoke test is the gate — no manual approval.
# Do not hand-edit — regenerate via /setup-coolify (rerun) instead.
#
# NOTE: NEXT_PUBLIC_BASE_URL (and any other env-specific value) is intentionally
# NOT passed as a --build-arg. Same-image promotion requires identical image bytes
# across staging and production; env-specific values flow through DOPPLER_TOKEN at
# container startup. See skillmap/Dockerfile for the rationale.
# Exception: GIT_SHA and BUILD_TIMESTAMP are identity-only build-args (same commit
# hash and timestamp for staging and production) — they do not break same-image promotion.
name: Deploy

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 8 * * 1'   # Monday 8am UTC — weekly INV-01 drift check

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: \${{ steps.tag.outputs.short_sha }}
      digest: \${{ steps.build.outputs.digest }}
    steps:
      - uses: actions/checkout@v4
      - id: tag
        run: echo "short_sha=\${GITHUB_SHA:0:7}" >> \$GITHUB_OUTPUT
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: \${{ github.actor }}
          password: \${{ secrets.GITHUB_TOKEN }}
      - id: build
        uses: docker/build-push-action@v6
        with:
          context: $BUILD_CONTEXT
          file: $BUILD_DOCKERFILE
          push: true
          tags: $REGISTRY_IMAGE_NAME:\${{ steps.tag.outputs.short_sha }}
          # GIT_SHA and BUILD_TIMESTAMP are identity-only build-args (not env-specific).
          # They bake OCI revision/created labels into the image without affecting
          # same-image promotion — their values are identical for staging and production.
          build-args: |
            GIT_SHA=\${{ steps.tag.outputs.short_sha }}
            BUILD_TIMESTAMP=\${{ github.event.head_commit.timestamp }}

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    env:
      COOLIFY_API_KEY: \${{ secrets.COOLIFY_API_KEY }}
      COOLIFY_URL: $COOLIFY_URL
      STAGING_APP_UUID: $STAGING_APP_UUID
      TAG: \${{ needs.build.outputs.tag }}
      DIGEST: \${{ needs.build.outputs.digest }}
      STAGING_DOMAIN: $STAGING_DOMAIN
    steps:
      - name: Set image tag on staging app
        run: |
          echo "Deploying tag=\$TAG digest=\$DIGEST"
          curl -sfS -X PATCH "\$COOLIFY_URL/api/v1/applications/\$STAGING_APP_UUID" \\
            -H "Authorization: Bearer \$COOLIFY_API_KEY" \\
            -H "Content-Type: application/json" \\
            -d "{\\"docker_registry_image_tag\\":\\"\$TAG\\"}"
      - name: Deploy staging + wait for Coolify
        run: |
          DEPLOY_RESPONSE=\$(curl -sfS "\$COOLIFY_URL/api/v1/deploy?uuid=\$STAGING_APP_UUID&force=false" \\
            -H "Authorization: Bearer \$COOLIFY_API_KEY")
          DEPLOYMENT_UUID=\$(echo "\$DEPLOY_RESPONSE" | jq -r '.deployments[0].deployment_uuid')
          echo "Triggered staging deploy: deployment_uuid=\$DEPLOYMENT_UUID"
          sleep 5
          timed_out=1
          for i in \$(seq 1 36); do
            STATUS=\$(curl -sfS "\$COOLIFY_URL/api/v1/deployments/\$DEPLOYMENT_UUID" \\
              -H "Authorization: Bearer \$COOLIFY_API_KEY" \\
              | jq -r '.status' 2>/dev/null || echo "unknown")
            echo "[\$i/36] status=\$STATUS"
            if [ "\$STATUS" = "finished" ]; then
              echo "Coolify deploy finished"; timed_out=0; break
            elif [ "\$STATUS" = "failed" ] || [ "\$STATUS" = "cancelled" ]; then
              echo "Coolify deploy \$STATUS: deployment_uuid=\$DEPLOYMENT_UUID" >&2
              echo "View in Coolify UI: \$COOLIFY_URL" >&2
              exit 1
            fi
            sleep 10
          done
          if [ "\$timed_out" -eq 1 ]; then
            echo "Coolify deploy timed out after 6 minutes: deployment_uuid=\$DEPLOYMENT_UUID" >&2
            echo "View in Coolify UI: \$COOLIFY_URL" >&2
            exit 1
          fi
      - name: Smoke test staging
        run: |
          for i in \$(seq 1 12); do
            sleep 30
            if curl -sfS "https://\$STAGING_DOMAIN$HEALTH_CHECK_PATH" -o /dev/null; then
              echo "Staging healthy on attempt \$i"; exit 0
            fi
            echo "Wait \$i/12 ..."
          done
          echo "Staging did not respond within 6min" >&2; exit 1
      - name: Assert staging version
        run: |
          HEALTH_BODY=\$(curl -sfS "https://\$STAGING_DOMAIN$HEALTH_CHECK_PATH")
          VERSION=\$(echo "\$HEALTH_BODY" | jq -r '.version // empty')
          if [ -z "\$VERSION" ]; then
            echo "SKIP version-assert: health response has no 'version' field"
            exit 0
          fi
          EXPECTED="sha-\$TAG"
          if [ "\$VERSION" = "\$EXPECTED" ]; then
            echo "OK   version-assert: version=\$VERSION"
          else
            echo "FAIL version-assert: expected=\$EXPECTED actual=\$VERSION" >&2
            exit 1
          fi

  deploy-production:
    needs: [deploy-staging, build]
    runs-on: ubuntu-latest
    env:
      COOLIFY_API_KEY: \${{ secrets.COOLIFY_API_KEY }}
      COOLIFY_URL: $COOLIFY_URL
      PROD_APP_UUID: $PROD_APP_UUID
      TAG: \${{ needs.build.outputs.tag }}
      DIGEST: \${{ needs.build.outputs.digest }}
      PROD_DOMAIN: $PROD_DOMAIN
    steps:
      - name: Set same image tag on production app (no rebuild)
        run: |
          echo "Deploying tag=\$TAG digest=\$DIGEST"
          curl -sfS -X PATCH "\$COOLIFY_URL/api/v1/applications/\$PROD_APP_UUID" \\
            -H "Authorization: Bearer \$COOLIFY_API_KEY" \\
            -H "Content-Type: application/json" \\
            -d "{\\"docker_registry_image_tag\\":\\"\$TAG\\"}"
      - name: Deploy production + wait for Coolify
        run: |
          DEPLOY_RESPONSE=\$(curl -sfS "\$COOLIFY_URL/api/v1/deploy?uuid=\$PROD_APP_UUID&force=false" \\
            -H "Authorization: Bearer \$COOLIFY_API_KEY")
          DEPLOYMENT_UUID=\$(echo "\$DEPLOY_RESPONSE" | jq -r '.deployments[0].deployment_uuid')
          echo "Triggered production deploy: deployment_uuid=\$DEPLOYMENT_UUID"
          sleep 5
          timed_out=1
          for i in \$(seq 1 36); do
            STATUS=\$(curl -sfS "\$COOLIFY_URL/api/v1/deployments/\$DEPLOYMENT_UUID" \\
              -H "Authorization: Bearer \$COOLIFY_API_KEY" \\
              | jq -r '.status' 2>/dev/null || echo "unknown")
            echo "[\$i/36] status=\$STATUS"
            if [ "\$STATUS" = "finished" ]; then
              echo "Coolify deploy finished"; timed_out=0; break
            elif [ "\$STATUS" = "failed" ] || [ "\$STATUS" = "cancelled" ]; then
              echo "Coolify deploy \$STATUS: deployment_uuid=\$DEPLOYMENT_UUID" >&2
              echo "View in Coolify UI: \$COOLIFY_URL" >&2
              exit 1
            fi
            sleep 10
          done
          if [ "\$timed_out" -eq 1 ]; then
            echo "Coolify deploy timed out after 6 minutes: deployment_uuid=\$DEPLOYMENT_UUID" >&2
            echo "View in Coolify UI: \$COOLIFY_URL" >&2
            exit 1
          fi
      - name: Smoke test production
        run: |
          for i in \$(seq 1 12); do
            sleep 30
            if curl -sfS "https://\$PROD_DOMAIN$HEALTH_CHECK_PATH" -o /dev/null; then
              echo "Production healthy on attempt \$i"; exit 0
            fi
            echo "Wait \$i/12 ..."
          done
          echo "Production did not respond within 6min" >&2; exit 1
      - name: Assert production version
        run: |
          HEALTH_BODY=\$(curl -sfS "https://\$PROD_DOMAIN$HEALTH_CHECK_PATH")
          VERSION=\$(echo "\$HEALTH_BODY" | jq -r '.version // empty')
          if [ -z "\$VERSION" ]; then
            echo "SKIP version-assert: health response has no 'version' field"
            exit 0
          fi
          EXPECTED="sha-\$TAG"
          if [ "\$VERSION" = "\$EXPECTED" ]; then
            echo "OK   version-assert: version=\$VERSION"
          else
            echo "FAIL version-assert: expected=\$EXPECTED actual=\$VERSION" >&2
            exit 1
          fi

  verify-promotion:
    # INV-04: assert staging and production are on the same image tag before cleanup.
    # Runs after both deploys complete. Hard-fails if either app's docker_registry_image_tag
    # differs from the build tag — blocks ghcr-cleanup so tags are preserved for debugging.
    needs: [deploy-staging, deploy-production, build]
    runs-on: ubuntu-latest
    env:
      COOLIFY_API_KEY: \${{ secrets.COOLIFY_API_KEY }}
      COOLIFY_URL: $COOLIFY_URL
      STAGING_APP_UUID: $STAGING_APP_UUID
      PROD_APP_UUID: $PROD_APP_UUID
      TAG: \${{ needs.build.outputs.tag }}
    steps:
      - name: Assert same image tag on staging and production
        run: |
          set -e
          failed=0
          for uuid in "\$STAGING_APP_UUID" "\$PROD_APP_UUID"; do
            actual=\$(curl -sfS "\$COOLIFY_URL/api/v1/applications/\$uuid" \\
              -H "Authorization: Bearer \$COOLIFY_API_KEY" \\
              | jq -r '.docker_registry_image_tag' 2>/dev/null || echo "")
            if [ "\$actual" = "\$TAG" ]; then
              echo "OK   verify-promotion uuid=\$uuid tag=\$actual"
            else
              echo "FAIL verify-promotion uuid=\$uuid expected=\$TAG actual=\$actual"
              failed=1
            fi
          done
          if [ "\$failed" -eq 1 ]; then
            echo "FAIL verify-promotion: diverged tags detected — ghcr-cleanup blocked" >&2
            exit 1
          fi

  ghcr-cleanup:
    needs: verify-promotion
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Keep last $RETENTION GHCR tags
        uses: actions/delete-package-versions@v5
        with:
          package-name: $PACKAGE
          package-type: container
          min-versions-to-keep: $RETENTION

  drift-check:
    # Runs on the weekly schedule only — never on push.
    # INV-01: each Coolify app must hold exactly one env var (DOPPLER_TOKEN).
    # Any other var silently overrides Doppler values at container start.
    # If this job fails, run /setup-coolify (provision) in the target repo to clean up.
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    env:
      COOLIFY_API_KEY: \${{ secrets.COOLIFY_API_KEY }}
      COOLIFY_URL: $COOLIFY_URL
      STAGING_APP_UUID: $STAGING_APP_UUID
      PROD_APP_UUID: $PROD_APP_UUID
    steps:
      - name: INV-01 — verify only DOPPLER_TOKEN is set in each Coolify app
        run: |
          set -e
          failed=0
          for uuid in "\$STAGING_APP_UUID" "\$PROD_APP_UUID"; do
            stale=\$(curl -sfS "\$COOLIFY_URL/api/v1/applications/\$uuid/envs" \\
              -H "Authorization: Bearer \$COOLIFY_API_KEY" \\
              | jq -r '(if type == "array" then . else (.data // []) end) | [.[] | select(.key != "DOPPLER_TOKEN") | .key] | unique | join(" ")' \\
              2>/dev/null || echo "")
            if [ -n "\$stale" ]; then
              echo "FAIL INV-01 uuid=\$uuid: stale vars found: \$stale"
              echo "     Fix: run /setup-coolify (provision) in the target repo to remove them."
              failed=1
            else
              echo "OK   INV-01 uuid=\$uuid (DOPPLER_TOKEN only)"
            fi
          done
          exit \$failed
YAML

# Validate output is parseable YAML
python3 -c "import yaml; yaml.safe_load(open('$OUT_PATH'))" >/dev/null

# Defensive: ensure no NEXT_PUBLIC_BASE_URL appears as a build-arg (same-image promotion guarantee)
if grep -qE 'NEXT_PUBLIC_BASE_URL\s*=' "$OUT_PATH" 2>/dev/null; then
  if grep -nE 'NEXT_PUBLIC_BASE_URL' "$OUT_PATH" | grep -vE '^[0-9]+:\s*#' >/dev/null 2>&1; then
    echo "ERROR: generated workflow references NEXT_PUBLIC_BASE_URL outside of a comment — this breaks same-image promotion." >&2
    exit 1
  fi
fi

echo "WROTE $OUT_PATH"
echo "  build context: $BUILD_CONTEXT  dockerfile: $BUILD_DOCKERFILE"
echo "  build: ghcr.io tag = commit short SHA (identity build-args only — runtime env via Doppler)"
echo "  deploy-staging: same tag -> staging app $STAGING_APP_UUID"
echo "  deploy-production: SAME tag -> production app $PROD_APP_UUID (auto after staging smoke test)"
echo "  ghcr-cleanup: keep last $RETENTION tags of $PACKAGE"
